# Generated by Django 3.2.3 on 2021-06-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=300)),
                ('author', models.CharField(max_length=30)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.CharField(max_length=20)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('update_by', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'board_test',
            },
        ),
    ]
