# Generated by Django 3.2.3 on 2021-06-09 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myboard',
            options={'ordering': ['-create_at']},
        ),
    ]
