# Generated by Django 3.2.3 on 2021-06-08 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_auto_20210607_1019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
