# Generated by Django 3.2.3 on 2021-06-14 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profiles',
            table='cccr_user',
        ),
    ]
